### PR TITLE
Format using shfmt, lint using shellcheck

### PR DESCRIPTION
**Pull request by vladimyr**
http://iscodeclean.ynaas.com 😉

### CODE REVIEW

**Comment by izabera** [comment]
I appreciate the time and effort you put into this but, to be entirely honest, I don't agree at all with many of the changes you proposed.

- I wasn't aware of the editor config thing.  I don't think it's the project's duty to mandate how people are supposed to write their code.  Also I wasn't really expecting people to want to write more of this code at all.
- I don't think a lot of utility comes out of that makefile.  It doesn't build anything, it ignores the exit status of the commands it runs, and all the targets are phony except for fmt which you probably forgot.
- = is equivalent to == in every shell that supports [[, and there's no reason to prefer one over the other. I am aware that ksh93 claims that = is obsolete and recommends to use == instead, but I find that just as silly.
- `[[ -e $host ]] && cat "$host" || cat idk` tries to execute the second cat as a fallback to the first one in case something goes wrong.  I don't necessarily think this will happen but it makes sense to use this form rather than if-then-else.  Perhaps it would make sense to remove the check entirely.

Thank you for pointing out the tabs in lines 25 and 26, I completely missed that.  Will fix.

**Comment by vladimyr** [comment]
> I appreciate the time and effort you put into this but, to be entirely honest, I don't agree at all with many of the changes you proposed.

That is fine. I didn't spend too much time doing it anyway. Addressing your points would require more time and while I'm usually all for having fruitful technical conversations online I'll pass this time because frankly I'm put off by your tone.
FWIW there is a very good reason why shellcheck instructs one to use:
```sh
([[ -e $host ]] && cat "$host") || cat idk
```
instead of:
```
[[ -e $host ]] && cat "$host" || cat idk
```

**Comment by izabera** [comment]
> FWIW there is a very good reason why shellcheck instructs one to use:
> 
> ```shell
> ([[ -e $host ]] && cat "$host") || cat idk
> ```
> 
> instead of:
> 
> ```
> [[ -e $host ]] && cat "$host" || cat idk
> ```

@vladimyr 
I am aware of the reason.  I understand that the second cat is executed if either `[[ -e $host ]]` or `cat "$host"` fail.  I told you that the second cat is executed as a backup in case the first fails.  Also your example uses an extra subshell that should have been `{ }` instead.

**Comment by vladimyr** [comment]
> Also your example uses an extra subshell that should have been `{ }` instead.

Excellent observation, yup that could/should be avoided 👍 
OTOH I tend to agree with [https://github.com/koalaman/shellcheck/wiki/SC2015](https://github.com/koalaman/shellcheck/wiki/SC2015#user-content-boring-detail:~:text=(More%20strictly%2C%20the%20parentheses%20should%20be,subshell%2C%20but%20that's%20ugly%20and%20boring.)) 🙃

**Comment by vladimyr** [comment]
> I am aware of the reason. I understand that the second cat is executed if either `[[ -e $host ]]` or `cat "$host"` fail. I told you that the second cat is executed as a backup in case the first fails.

Not everyone is so here is an unpopular opinion: code is written for humans to read (those who aren't aware of all shell scripting quirks too).

**Pull request closed without merging**
